extends: standard
parserOptions:
    sourceType: script
env:
    node: true
rules:
    no-multi-spaces:
        - error
        - exceptions:
            VariableDeclarator: true
    space-before-function-paren:
        - off
