extends: standard
parserOptions:
    sourceType: script
env:
    node: true
rules:
    indent:
        - error
        - 2
    no-multi-spaces: 
        - error
        - exceptions: 
            VariableDeclarator: true
    space-before-function-paren:
        - off
