before_script:
  - sudo apt-get update -y
  - sudo apt-get install -y libssl-dev build-essential wget
  - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash
  - source /root/.bashrc
  - nvm install node
  - nvm use node
  - npm install mocha -g

nodejs_run:
  stage: test
  script:
    - npm install
    - npm test