image: node:6.2.2

cache:
  paths:
    - node_modules/

stages:
  - test

before_script:
  - npm install

nodejs_mocha:
  stage: test
  script:
    - npm run mocha

nodejs_lint:
  stage: test
  script:
    - npm run eslint