image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - test

before_script:
  - npm install

nodejs_unit_test:
  stage: test
  script:
    - npm run coverage
  tags:
    - nodejs

nodejs_lint:
  stage: test
  script:
    - npm run lint
  tags:
    - nodejs
